spring.application.name=broker
server.port=8081

catering.service.url=http://localhost:8082
venue.service.url=http://localhost:8083

spring.datasource.url=jdbc:sqlserver://broker.database.windows.net:1433;database=broker;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=broker_login
spring.datasource.password=Password!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate instellingen
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Enable scheduling for SAGA retry mechanism
spring.task.scheduling.thread-name-prefix=retry-scheduler-
spring.task.scheduling.pool.size=2