spring.application.name=broker
server.port=${PORT:8080}

catering.service.url=https://catering-app-g7ebhgeseahsaeev.switzerlandnorth-01.azurewebsites.net
venue.service.url=https://venue-app-h7ecfyg4f2gbb5ey.switzerlandnorth-01.azurewebsites.net

spring.datasource.url=jdbc:sqlserver://broker.database.windows.net:1433;database=broker;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=broker_login
spring.datasource.password=Password!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate instellingen
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Enable scheduling for SAGA retry mechanism
spring.task.scheduling.thread-name-prefix=retry-scheduler-
spring.task.scheduling.pool.size=2