spring.application.name=Venue
server.port=${PORT:8080}

# Dit moet matchen met de export in je .bashrc
spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT1}
spring.cloud.azure.cosmos.key=${COSMOS_KEY1}
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-sbs2gjpltu7qtvut.us.auth0.com/
logging.level.org.springframework.security=DEBUG